version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - redisdb

  redisdb:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redisdb-container
    command: ["redis-server", "--bind", "redisdb", "--port", "6379"]
    volumes:
      - ./data:/data
